import{test,expect}from'@playwright/test';import{mkdir,writeFile,readFile}from'node:fs/promises';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';
const stage=process.env.CHART_STAGE??'c5';
const h=JSON.parse(await readFile('public/data/history.json','utf8'));
const state=(p:any)=>p.evaluate(()=> (window as any).chartTest.snapshot());
test('真实K线、完整未来、公开坐标和本机交互',async({page,browser},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?test=1');await expect.poll(async()=>(await state(page))?.historyCount).toBe(1344);let s=await state(page);expect(s.supportCount).toBe(1441);expect(s.historyLastTime).toBe(h.end_time-900);expect(s.anchorX).toBeGreaterThan(0);expect(s.priceY).not.toBeNull();
 const pixelCount=()=>page.locator('#chart canvas').first().evaluate((c:HTMLCanvasElement)=>{const d=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=4)if((d[i]===86&&d[i+1]===190)||(d[i]===235&&d[i+1]===130))n++;return n;});await expect.poll(pixelCount).toBeGreaterThan(100);const pixels=await pixelCount();
 const box=(await page.locator('#chart').boundingBox())!;const before=s.range.to-s.range.from;await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.wheel(0,-250);await expect.poll(async()=>{s=await state(page);return s.range.to-s.range.from;}).not.toBe(before);
 const from=(await state(page)).range.from;await page.mouse.down();await page.mouse.move(box.x+box.width*.65,box.y+box.height*.5,{steps:12});await page.mouse.up();await expect.poll(async()=>(await state(page)).range.from).not.toBe(from);
 await page.getByRole('button',{name:'重置视图'}).click();await page.mouse.move(box.x+box.width*.35,box.y+box.height*.5);await expect(page.locator('#hover')).toContainText('真实历史');
 await mkdir(`artifacts/${stage}`,{recursive:true});const shot=`artifacts/${stage}/history-${info.project.name}.png`;await page.screenshot({path:shot,fullPage:true,scale:'device'});
 await page.evaluate(({from,to})=>(window as any).chartTest.setRange(from,to),{from:h.end_time+900,to:h.end_time+86400});await expect.poll(async()=>(await state(page)).priceY).not.toBeNull();
 const sources=execFileSync('git',['ls-files','--cached','--others','--exclude-standard'],{encoding:'utf8'}).trim().split('\n');const hashes:Record<string,string>={};for(const f of sources)hashes[f]=createHash('sha256').update(await readFile(f)).digest('hex');await writeFile(`artifacts/${stage}/history-${info.project.name}.json`,JSON.stringify({result:'PASS',browser:browser.version(),viewport:page.viewportSize(),dpr:await page.evaluate(()=>devicePixelRatio),timezone:'Asia/Shanghai',dataset_id:h.dataset_id,head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),source_hashes:hashes,screenshot:shot,canvas_colored_pixels:pixels,snapshot:await state(page)},null,2));expect(errors).toEqual([]);
});
async function aligned(page:any){await expect.poll(async()=>(await state(page)).vertices.length).toBe(97);const s=await state(page);let checked=0;for(const actual of s.vertices){const expected=s.coordinateCheck.find((e:any)=>e.time===actual.time);if(!expected)continue;expect(Math.abs(actual.x-expected.x)).toBeLessThanOrEqual(1);expect(Math.abs(actual.outerUpper-expected.outerUpper)).toBeLessThanOrEqual(1);if(expected.candleY!==null)expect(Math.abs(expected.candleY-expected.supportY)).toBeLessThanOrEqual(1);checked++;}expect(checked).toBe(96);return s;}
async function evidence(page:any,browser:any,info:any,name:string){await mkdir(`artifacts/${stage}`,{recursive:true});const path=`artifacts/${stage}/${name}-${info.project.name}.png`;await page.screenshot({path,fullPage:true,scale:'device'});await writeFile(path+'.json',JSON.stringify({result:'PASS',candidate_visual_acceptance:true,user_approved:false,command:'npm run test:e2e',browser:browser.version(),viewport:page.viewportSize(),dpr:await page.evaluate(()=>devicePixelRatio),timezone:await page.evaluate(()=>Intl.DateTimeFormat().resolvedOptions().timeZone),dataset_id:h.dataset_id,head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),code_receipt:`artifacts/${stage}/code-receipt.json`,screenshot:path,sha256:createHash('sha256').update(await readFile(path)).digest('hex'),snapshot:await state(page)},null,2));}
test('多路径、区间重绘、价轴、DPR和纯未来',async({page,browser},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?test=1');await expect(page.getByRole('checkbox',{name:'冲高回落'})).toBeChecked();await aligned(page);await evidence(page,browser,info,'paths-bands');const box=(await page.locator('#chart').boundingBox())!;
 let s=await state(page),draws=s.bandDraws;await page.mouse.move(box.x+box.width*.7,box.y+box.height*.5);await page.mouse.wheel(0,-240);await expect.poll(async()=>(await state(page)).bandDraws).toBeGreaterThan(draws);await aligned(page);
 draws=(await state(page)).bandDraws;await page.mouse.down();await page.mouse.move(box.x+box.width*.58,box.y+box.height*.5,{steps:12});await page.mouse.up();await expect.poll(async()=>(await state(page)).bandDraws).toBeGreaterThan(draws);await aligned(page);
 s=await state(page);const spacing=Math.abs(s.priceY2-s.priceY);await page.mouse.move(box.x+box.width-s.priceWidth/2,box.y+box.height*.45);await page.mouse.down();await page.mouse.move(box.x+box.width-s.priceWidth/2,box.y+box.height*.45+90,{steps:15});await page.mouse.up();await expect.poll(async()=>{const v=await state(page);return Math.abs(v.priceY2-v.priceY);}).not.toBe(spacing);await aligned(page);await evidence(page,browser,info,'zoom-price-scale');
 const old=(await state(page)).bandDraws;await page.setViewportSize({width:1100,height:820});await expect.poll(async()=>(await state(page)).bandDraws).toBeGreaterThan(old);await aligned(page);
 for(const name of['冲高回落','下探回升','持续突破'])await page.getByRole('checkbox',{name}).uncheck();expect((await state(page)).visiblePaths).toEqual([]);await page.getByRole('button',{name:'重置视图'}).click();await page.evaluate(({from,to})=>(window as any).chartTest.setRange(from,to),{from:h.end_time+900,to:h.end_time+86400});await aligned(page);s=await state(page);expect(s.priceY).not.toBeNull();const futureBox=(await page.locator('#chart').boundingBox())!;const visible=s.vertices.filter((v:any)=>v.x>=0&&v.x<futureBox.width-s.priceWidth);for(const v of visible){expect(v.outerUpper).toBeGreaterThanOrEqual(0);expect(v.outerLower).toBeLessThan(futureBox.height);}
 await evidence(page,browser,info,'all-hidden-future');expect(errors).toEqual([]);
});
const fdata=JSON.parse(await readFile('public/data/forecast.demo.json','utf8'));
const gdata=JSON.parse(await readFile('public/data/grids.demo.json','utf8'));
test('网格20次切换、窗口独立、重载生命周期与任意模式',async({page,browser},info)=>{await page.goto('/?test=1');await expect(page.locator('#load-status')).toContainText('已校验');const initial=await state(page);for(const scheme of gdata.schemes){await page.getByLabel('网格方案',{exact:true}).selectOption(scheme.id);await expect.poll(async()=>(await state(page)).gridPrices).toEqual(scheme.levels);await evidence(page,browser,info,'grid-'+scheme.id);}
 for(let i=0;i<20;i++){const s=gdata.schemes[i%gdata.schemes.length];await page.getByLabel('网格方案',{exact:true}).selectOption(s.id);await page.getByLabel('未来展示窗口').selectOption(String([6,12,24][i%3]));await expect.poll(async()=>Number((await state(page)).visibleTime.to)).toBe(h.end_time+[6,12,24][i%3]*3600);const d=await state(page);expect(d.gridLineCount).toBe(s.interval_count+1);expect(d.gridPrices).toEqual(s.levels);expect(d.activeCharts).toBe(1);expect(d.createdCharts).toBe(initial.createdCharts);expect(d.subscriptions).toBe(1);expect(d.canvasCount).toBe(initial.canvasCount);expect(Number(d.visibleTime.to)).toBe(h.end_time+[6,12,24][i%3]*3600);}
 const before=(await state(page)).gridPrices;await page.getByRole('checkbox',{name:'冲高回落'}).uncheck();expect((await state(page)).gridPrices).toEqual(before);await page.getByRole('checkbox',{name:'显示网格'}).uncheck();expect((await state(page)).gridLineCount).toBe(0);await page.getByRole('checkbox',{name:'显示网格'}).check();
 for(let i=0;i<5;i++){const created=(await state(page)).createdCharts;await page.getByRole('button',{name:'重载文件'}).click();await expect.poll(async()=>(await state(page)).createdCharts).toBe(created+1);const d=await state(page);expect(d.activeCharts).toBe(1);expect(d.subscriptions).toBe(1);expect(d.destroyedCharts).toBe(d.createdCharts-1);expect(d.visiblePaths).not.toContain('rise-fade');expect(d.gridPrices).toEqual(before);expect(await page.getByRole('checkbox',{name:'冲高回落'}).count()).toBe(1);}
 const {seal}=await import('../../src/contracts');const custom=structuredClone(gdata);custom.schemes.push({...custom.schemes[0],id:'custom-four',name:'第四配置',mode:{id:'custom-four',label:'任意自定义模式'}});const sealed=await seal(custom);await page.route('**/data/grids.demo.json',route=>route.fulfill({json:sealed}));await page.getByRole('button',{name:'重载文件'}).click();await expect(page.locator('#scheme option')).toHaveCount(4);await page.getByLabel('网格方案',{exact:true}).selectOption('custom-four');await expect(page.locator('#grid-summary')).toContainText('任意自定义模式');expect((await state(page)).gridPrices).toEqual(custom.schemes[3].levels);
});
test('缺文件、坏JSON、错误关联清理受影响图层并恢复',async({page,browser},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?test=1');await expect(page.locator('#load-status')).toContainText('已校验');
 for(const [file,body,missing]of[['grids.demo.json',JSON.stringify({...gdata,history_dataset_id:'wrong'}),false],['forecast.demo.json','{broken',false],['history.json','',true]]as const){await page.route('**/data/'+file,route=>route.fulfill({status:missing?404:200,contentType:'application/json',body}));await page.getByRole('button',{name:'重载文件'}).click();await expect(page.locator('#errors')).toContainText(file);const s=await state(page);expect(s.gridLineCount).toBe(0);if(file!=='grids.demo.json')expect(s.pathCount).toBe(0);expect(s.historyCount).toBe(file==='history.json'?0:1344);await evidence(page,browser,info,'error-'+file);await page.unroute('**/data/'+file);await page.getByRole('button',{name:'重载文件'}).click();await expect(page.locator('#errors')).toBeHidden();await expect.poll(async()=>(await state(page)).pathCount).toBe(3);}
 expect(errors).toEqual([]);
});
test('阻断外网仍可加载重载且文件不被交互改写',async({page})=>{const requests:string[]=[];await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname!=='127.0.0.1'){requests.push(url.href);return route.abort();}return route.continue();});await page.goto('/?test=1');await expect(page.locator('#load-status')).toContainText('已校验');await page.getByRole('button',{name:'重载文件'}).click();await expect(page.locator('#load-status')).toContainText('已校验');expect(requests).toEqual([]);expect(JSON.parse(await readFile('public/data/history.json','utf8'))).toEqual(h);expect(JSON.parse(await readFile('public/data/forecast.demo.json','utf8'))).toEqual(fdata);expect(JSON.parse(await readFile('public/data/grids.demo.json','utf8'))).toEqual(gdata);});
test('重载竞态只提交最新结果',async({page})=>{await page.goto('/?test=1');await expect(page.locator('#load-status')).toContainText('已校验');let calls=0;await page.route('**/data/forecast.demo.json',async route=>{calls++;if(calls===1){await new Promise(r=>setTimeout(r,400));await route.fulfill({body:'{old invalid',contentType:'application/json'}).catch(()=>{});}else await route.fulfill({json:fdata});});await page.getByRole('button',{name:'重载文件'}).click();await expect.poll(()=>calls).toBe(1);await page.getByRole('button',{name:'重载文件'}).click();await expect.poll(()=>calls).toBe(2);await expect(page.locator('#load-status')).toContainText('已校验');await page.waitForTimeout(450);await expect(page.locator('#errors')).toBeHidden();expect((await state(page)).pathCount).toBe(3);expect((await state(page)).activeCharts).toBe(1);});
