import{test,expect}from'@playwright/test';import{mkdir,writeFile,readFile}from'node:fs/promises';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';
const stage=process.env.CHART_STAGE??'c5';
const h=JSON.parse(await readFile('public/data/history.json','utf8'));
const state=(p:any)=>p.evaluate(()=> (window as any).chartTest.snapshot());
test('真实K线、完整未来、公开坐标和本机交互',async({page,browser},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?test=1');await expect.poll(async()=>(await state(page))?.historyCount).toBe(1344);let s=await state(page);expect(s.supportCount).toBe(1441);expect(s.historyLastTime).toBe(h.end_time-900);expect(s.anchorX).toBeGreaterThan(0);expect(s.priceY).not.toBeNull();
 const pixelCount=()=>page.locator('#chart canvas').first().evaluate((c:HTMLCanvasElement)=>{const d=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=4)if((d[i]===86&&d[i+1]===190)||(d[i]===235&&d[i+1]===130))n++;return n;});await expect.poll(pixelCount).toBeGreaterThan(100);const pixels=await pixelCount();
 const box=(await page.locator('#chart').boundingBox())!;const before=s.range.to-s.range.from;await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.wheel(0,-250);await expect.poll(async()=>{s=await state(page);return s.range.to-s.range.from;}).not.toBe(before);
 const from=(await state(page)).range.from;await page.mouse.down();await page.mouse.move(box.x+box.width*.65,box.y+box.height*.5,{steps:12});await page.mouse.up();await expect.poll(async()=>(await state(page)).range.from).not.toBe(from);
 await page.getByRole('button',{name:'重置视图'}).click();await page.mouse.move(box.x+box.width*.35,box.y+box.height*.5);await expect(page.locator('#hover')).toContainText('真实历史');
 await mkdir(`artifacts/${stage}`,{recursive:true});const shot=`artifacts/${stage}/history-${info.project.name}.png`;await page.screenshot({path:shot,fullPage:true,scale:'device'});
 await page.evaluate(({from,to})=>(window as any).chartTest.setRange(from,to),{from:h.end_time+900,to:h.end_time+86400});await expect.poll(async()=>(await state(page)).priceY).not.toBeNull();
 const sources=execFileSync('git',['ls-files','--cached','--others','--exclude-standard'],{encoding:'utf8'}).trim().split('\n');const hashes:Record<string,string>={};for(const f of sources)hashes[f]=createHash('sha256').update(await readFile(f)).digest('hex');await writeFile(`artifacts/${stage}/history-${info.project.name}.json`,JSON.stringify({result:'PASS',browser:browser.version(),viewport:page.viewportSize(),dpr:await page.evaluate(()=>devicePixelRatio),timezone:'Asia/Shanghai',dataset_id:h.dataset_id,head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),source_hashes:hashes,screenshot:shot,canvas_colored_pixels:pixels,snapshot:await state(page)},null,2));expect(errors).toEqual([]);
});
async function aligned(page:any){await expect.poll(async()=>(await state(page)).vertices.length).toBe(97);const s=await state(page);let checked=0;for(const actual of s.vertices){const expected=s.coordinateCheck.find((e:any)=>e.time===actual.time);if(!expected)continue;expect(Math.abs(actual.x-expected.x)).toBeLessThanOrEqual(1);expect(Math.abs(actual.outerUpper-expected.outerUpper)).toBeLessThanOrEqual(1);if(expected.candleY!==null)expect(Math.abs(expected.candleY-expected.supportY)).toBeLessThanOrEqual(1);checked++;}expect(checked).toBe(96);return s;}
async function evidence(page:any,browser:any,info:any,name:string){await mkdir(`artifacts/${stage}`,{recursive:true});const path=`artifacts/${stage}/${name}-${info.project.name}.png`;await page.screenshot({path,fullPage:true,scale:'device'});await writeFile(path+'.json',JSON.stringify({result:'PASS',candidate_visual_acceptance:true,user_approved:false,command:'npm run test:e2e',browser:browser.version(),viewport:page.viewportSize(),dpr:await page.evaluate(()=>devicePixelRatio),timezone:await page.evaluate(()=>Intl.DateTimeFormat().resolvedOptions().timeZone),dataset_id:h.dataset_id,head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),code_receipt:`artifacts/${stage}/code-receipt.json`,screenshot:path,sha256:createHash('sha256').update(await readFile(path)).digest('hex'),snapshot:await state(page)},null,2));}
test('多路径、区间重绘、价轴、DPR和纯未来',async({page,browser},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?test=1');await expect(page.getByRole('checkbox',{name:'冲高回落'})).toBeChecked();await aligned(page);await evidence(page,browser,info,'paths-bands');const box=(await page.locator('#chart').boundingBox())!;
 let s=await state(page),draws=s.bandDraws;await page.mouse.move(box.x+box.width*.7,box.y+box.height*.5);await page.mouse.wheel(0,-240);await expect.poll(async()=>(await state(page)).bandDraws).toBeGreaterThan(draws);await aligned(page);
 draws=(await state(page)).bandDraws;await page.mouse.down();await page.mouse.move(box.x+box.width*.58,box.y+box.height*.5,{steps:12});await page.mouse.up();await expect.poll(async()=>(await state(page)).bandDraws).toBeGreaterThan(draws);await aligned(page);
 s=await state(page);const spacing=Math.abs(s.priceY2-s.priceY);await page.mouse.move(box.x+box.width-s.priceWidth/2,box.y+box.height*.45);await page.mouse.down();await page.mouse.move(box.x+box.width-s.priceWidth/2,box.y+box.height*.45+90,{steps:15});await page.mouse.up();await expect.poll(async()=>{const v=await state(page);return Math.abs(v.priceY2-v.priceY);}).not.toBe(spacing);await aligned(page);await evidence(page,browser,info,'zoom-price-scale');
 const old=(await state(page)).bandDraws;await page.setViewportSize({width:1100,height:820});await expect.poll(async()=>(await state(page)).bandDraws).toBeGreaterThan(old);await aligned(page);
 for(const name of['冲高回落','下探回升','持续突破'])await page.getByRole('checkbox',{name}).uncheck();expect((await state(page)).visiblePaths).toEqual([]);await page.getByRole('button',{name:'重置视图'}).click();await page.evaluate(({from,to})=>(window as any).chartTest.setRange(from,to),{from:h.end_time+900,to:h.end_time+86400});await aligned(page);s=await state(page);expect(s.priceY).not.toBeNull();const futureBox=(await page.locator('#chart').boundingBox())!;const visible=s.vertices.filter((v:any)=>v.x>=0&&v.x<futureBox.width-s.priceWidth);for(const v of visible){expect(v.outerUpper).toBeGreaterThanOrEqual(0);expect(v.outerLower).toBeLessThan(futureBox.height);}
 await evidence(page,browser,info,'all-hidden-future');expect(errors).toEqual([]);
});
