import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';import net from'node:net';import{backup,restore}from'../scripts/m1-backup.mjs';
test('backup restores reference closure with independent identities and excludes runtime activation',async t=>{const root=await fs.mkdtemp(path.join(await fs.realpath(os.tmpdir()),'mfv-backup-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const data=path.join(root,'data'),target=path.join(root,'backup');await fs.mkdir(path.join(data,'data-source'),{recursive:true});await fs.mkdir(path.join(data,'forecast-runs'));await fs.mkdir(target);await fs.writeFile(path.join(data,'data-source/raw.json'),'SYNTHETIC SOURCE');await fs.writeFile(path.join(data,'forecast-runs/manifest.json'),'SYNTHETIC REFERENCE');const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const port=s.address().port;await new Promise(r=>s.close(r));const result=await backup({dataRoot:data,target,port,releaseId:'SYNTHETIC',maxBytes:1048576});assert.equal(result.status,'completed');assert.equal(result.manifest.kind,'local-recovery');const file=result.manifest.files.find(x=>x.name==='data-source/raw.json'),object=path.join(target,'objects',file.sha256);assert.notEqual((await fs.stat(object)).ino,(await fs.stat(path.join(data,file.name))).ino);const dest=path.join(root,'restore');const receipt=await restore({target,manifestFile:path.join(target,'manifests',result.manifest.id+'.json'),destination:dest,verify:async root=>({passed:(await fs.readFile(path.join(root,'data-source/raw.json'),'utf8'))==='SYNTHETIC SOURCE'})});assert.equal(receipt.activation_restored,false);await assert.rejects(()=>restore({target,manifestFile:path.join(target,'manifests',result.manifest.id+'.json'),destination:dest,verify:async()=>({passed:true})}));});

test('backup rejects overlapping, substituted and missing targets; preserves foreign lock',async t=>{
 const root=await fs.mkdtemp(path.join(await fs.realpath(os.tmpdir()),'mfv-backup-boundary-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const data=path.join(root,'data'),target=path.join(root,'backup');await fs.mkdir(data);await fs.mkdir(target);
 const {verifyBackupTarget}=await import('../scripts/m1-backup.mjs');
 await assert.rejects(()=>verifyBackupTarget({dataRoot:data,target:data}),/OVERLAPS/);
 await assert.rejects(()=>verifyBackupTarget({dataRoot:data,target:root}),/OVERLAPS/);
 await assert.rejects(()=>verifyBackupTarget({dataRoot:data,target:path.join(root,'absent')}),/ENOENT/);assert.equal(await fs.stat(path.join(root,'absent')).catch(()=>null),null);
 await assert.rejects(()=>verifyBackupTarget({dataRoot:data,target,deviceId:'wrong-device'}),/DEVICE_MISMATCH/);
 await fs.mkdir(path.join(target,'.backup-lock'));await fs.writeFile(path.join(target,'.backup-lock/owner.json'),'FOREIGN');
 assert.deepEqual(await backup({dataRoot:data,target,port:12345,releaseId:'SYNTHETIC'}),{status:'skipped',reason:'BACKUP_BUSY'});assert.equal(await fs.readFile(path.join(target,'.backup-lock/owner.json'),'utf8'),'FOREIGN');
});

test('bounded restore resumes exact objects after source deletion/modification and quarantines installation',async t=>{
 const root=await fs.mkdtemp(path.join(await fs.realpath(os.tmpdir()),'mfv-restore-resume-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const data=path.join(root,'data'),target=path.join(root,'backup'),home=path.join(root,'runtime');
 await fs.mkdir(path.join(data,'data-source'),{recursive:true});await fs.mkdir(path.join(data,'m1-candidates'));await fs.mkdir(target);await fs.mkdir(home);
 await fs.writeFile(path.join(data,'data-source/a'),'ORIGINAL-A');await fs.writeFile(path.join(data,'data-source/b'),'ORIGINAL-B');await fs.writeFile(path.join(data,'m1-candidates/input.json'),'CANDIDATE');await fs.writeFile(path.join(home,'installation.local.json'),'PAUSED CONFIG');await fs.writeFile(path.join(home,'release-manifest.json'),'RELEASE IDENTITY');
 const server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));
 const b=await backup({dataRoot:data,runtimeHome:home,target,port,releaseId:'SYNTHETIC'});assert.equal(b.manifest.runtime_included,true);
 await fs.unlink(path.join(data,'data-source/a'));await fs.writeFile(path.join(data,'data-source/b'),'MODIFIED');
 const args={target,manifestFile:path.join(target,'manifests',b.manifest.id+'.json'),destination:path.join(root,'restored'),verify:async dest=>({passed:(await fs.readFile(path.join(dest,'data-source/a'),'utf8'))==='ORIGINAL-A'&&(await fs.readFile(path.join(dest,'data-source/b'),'utf8'))==='ORIGINAL-B'})};
 const first=await restore({...args,maxFiles:1});assert.equal(first.status,'incomplete');assert.equal(first.cursor,1);
 const receipt=await restore({...args,resume:true});assert.equal(receipt.activation_restored,false);assert.ok(receipt.skipped.includes('runtime-snapshot/installation.local.json'));assert.equal(await fs.readFile(path.join(args.destination,'m1-candidates/input.json'),'utf8'),'CANDIDATE');assert.equal(await fs.readFile(path.join(args.destination,'runtime-snapshot/release-manifest.json'),'utf8'),'RELEASE IDENTITY');
});
