import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {caseStore} from '../scripts/m1-cases.mjs';import {createDisplayReader} from '../scripts/m1-display.mjs';import {createOutcomeStore} from '../scripts/m1-outcome-store.mjs';
const runId='m1-20260912T183644170Z-00000000-0000-4000-8000-000000000011';
test('mature case follows actual revision and source hashes; revocation and availability prevent consumption',async t=>{
 const root=await fs.mkdtemp(path.join(await fs.realpath(os.tmpdir()),'mfv-case-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const data=path.join(root,'data');await fs.mkdir(data);for(const name of ['forecast-runs','data-source','m1-outcomes'])await fs.cp(path.resolve('artifacts',name),path.join(data,name),{recursive:true});const before=process.env.MFV_DATA_ROOT;process.env.MFV_DATA_ROOT=data;t.after(()=>{if(before===undefined)delete process.env.MFV_DATA_ROOT;else process.env.MFV_DATA_ROOT=before;});
 const codeRoot=process.cwd(),reader=createDisplayReader({root:codeRoot,dataRoot:data}),outcome=createOutcomeStore({root:codeRoot,dataRoot:data}),run=await reader.readRun(runId,{includeEvaluation:false}),price=run.forecast.anchor_price,anchor=run.forecast.anchor_time;
 const capture=await outcome.capture(run,{transport:async({file})=>{await fs.writeFile(file,JSON.stringify({code:'0',msg:'SYNTHETIC CASE',data:Array.from({length:96},(_,i)=>[String((anchor+i*900)*1000),...Array(4).fill(String(price)),'10','1','100','1']).reverse()}));return '200';}});assert.equal(capture.status,'ok');const revision=await outcome.evaluateCapture(run,capture.capture_id);
 const store=caseStore({codeRoot,dataRoot:data}),value=await store.create(runId,revision.revision_id);assert.equal(value.actual_category,'narrow');assert.equal(value.end_time-value.start_time,86400);assert.equal(value.all_path_losses.length,6);assert.ok(Date.parse(value.available_at)>=Date.parse(revision.result.evaluated_at));
 assert.equal((await store.available('2026-09-12T18:39:00.000Z')).length,0);assert.equal((await store.available(new Date(Date.now()+1000).toISOString())).length,1);
 const oneCase=await store.freeze(value.features,new Date(Date.now()+1000).toISOString(),{predictor_version:'test',model:'test',reasoning_effort:'medium',additional_inputs:'none',feedback:'F1',lambda:0});
 assert.equal(oneCase.base.n,1);assert.deepEqual(oneCase.feedback.case_ids,[]);assert.equal(JSON.parse(oneCase.feedback.body).reason,'insufficient_nonzero_scale');
 await fs.mkdir(path.join(data,'m1-learning'),{recursive:true});await fs.writeFile(path.join(data,'m1-learning/controls.json'),JSON.stringify({disabled_scorers:[],revoked_revisions:[revision.revision_id],learning_disabled:true,effective_at:new Date().toISOString(),first_run_id:null}));
 await assert.rejects(()=>store.read(value.id),/SCORER_OR_REVISION_DISABLED/);assert.equal((await store.available(new Date(Date.now()+1000).toISOString())).length,0);
 const frozen=await store.freeze({x:1},new Date().toISOString(),{predictor_version:'test',model:'test',reasoning_effort:'medium',additional_inputs:'none',feedback:'F1',lambda:.5});assert.equal(frozen.lambda,0);assert.equal(frozen.feedback_mode,'F0');assert.equal(frozen.feedback,null);
 await store.recordFirstDisabledRun(runId);assert.equal((await store.controls()).first_run_id,runId);
});
