import{seal}from'../src/contracts.ts';
// Fixture v1: xorshift32, piecewise-linear templates, prices rounded to 8 decimals.
export async function generateDemo(h,seed=20260912){let state=seed>>>0;const random=()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return(state>>>0)/4294967296;};const round=x=>Number(x.toFixed(8));const p=h.candles.at(-1).close,t=h.end_time;
 const common={schema_version:'1.0.0',demo:true,source_kind:'synthetic_fixture',history_dataset_id:h.dataset_id,history_content_sha256:h.content_sha256,instrument:h.instrument,market_type:h.market_type,price_type:h.price_type,time_unit:'s',bar_seconds:900,generator_version:'fixture-v1-xorshift32-linear-8dp',seed,generated_at:h.downloaded_at,anchor_time:t,anchor_price:p,horizon_seconds:86400,step_seconds:900};
 const templates=[{id:'rise-fade',name:'冲高回落',description:'先上探，再逐步回落的固定演示路径',knots:[0,.022,.013,-.005]},{id:'dip-recover',name:'下探回升',description:'先下探，再修复回升的固定演示路径',knots:[0,-.018,-.009,.012]},{id:'breakout',name:'持续突破',description:'震荡抬升后继续向上的固定演示路径',knots:[0,.006,.02,.038]}];
 const scenarios=templates.map(({knots,...s})=>({...s,points:Array.from({length:96},(_,i)=>{const k=i+1,bounds=[0,24,48,96];const j=k<=24?0:k<=48?1:2;const u=(k-bounds[j])/(bounds[j+1]-bounds[j]);const shift=knots[j]+(knots[j+1]-knots[j])*u+(random()-.5)*.0012*Math.sin(Math.PI*u);return{time:t+k*900,price:round(p*(1+shift))};})}));
 const bands={kind:'illustrative',label:'示意区间，未经校准',points:Array.from({length:96},(_,i)=>{const values=scenarios.map(s=>s.points[i].price),u=(i+1)/96,center=p*(1+.008*u),half=p*(.002+.012*Math.sqrt(u));return{time:t+(i+1)*900,inner_lower:round(center-half),inner_upper:round(center+half),outer_lower:round(Math.min(...values,center-half)-p*.003*Math.sqrt(u)),outer_upper:round(Math.max(...values,center+half)+p*.003*Math.sqrt(u))};})};
 const forecast=await seal({...common,kind:'forecast_demo',label:'DEMO 演示未来，非交易信号',future_count:96,stages:[{id:'early',name:'初段 · 分化',start_time:t,end_time:t+21600},{id:'middle',name:'中段 · 演变',start_time:t+21600,end_time:t+43200},{id:'late',name:'后段 · 延伸',start_time:t+43200,end_time:t+86400}],scenarios,bands});
 const specs=[['neutral','中性区间','中性',.975,1.025,10,'arithmetic'],['long','上移区间','做多',.99,1.045,12,'geometric'],['short','下移区间','做空',.955,1.008,8,'arithmetic']];
 const schemes=specs.map(([id,name,label,lo,hi,n,distribution])=>{const lower=round(p*lo),upper=round(p*hi);return{id,name,mode:{id,label},initial_position_label:'仅作方向示意，未模拟底仓',lower_price:lower,upper_price:upper,distribution,interval_count:n,levels:Array.from({length:n+1},(_,i)=>i===0?lower:i===n?upper:round(distribution==='arithmetic'?lower+(upper-lower)*i/n:lower*(upper/lower)**(i/n)))};});
 return{forecast,grids:await seal({...common,kind:'grids_demo',label:'DEMO 网格配置，未接入收益评估',default_scheme_id:'neutral',schemes})};
}
