import fs from'node:fs/promises';import path from'node:path';import{readFrozen}from'./m1-archive.mjs';import{createDisplayReader}from'./m1-display.mjs';import{createOutcomeStore}from'./m1-outcome-store.mjs';import{readJson,readBytes,writeOnce,atomic,digest,canonical,exists,check}from'./m1-files.mjs';import{mainScenario,baseRate,feedback}from'./m1-learning.mjs';
export function caseStore({codeRoot,dataRoot}){
 const reader=createDisplayReader({root:codeRoot,dataRoot}),outcomes=createOutcomeStore({root:codeRoot,dataRoot}),home=path.join(dataRoot,'m1-cases');
 async function controls(){const p=path.join(dataRoot,'m1-learning/controls.json');return await exists(p)?await readJson(dataRoot,p):{disabled_scorers:[],revoked_revisions:[],learning_disabled:false};}
 async function verifiedSource(runId,revisionId){const control=await controls(),run=await reader.readRun(runId,{includeEvaluation:false});const revision=await outcomes.readRevision(run,revisionId);const scorer=revision.result.evaluation_version;check(!control.disabled_scorers.includes(scorer)&&!control.revoked_revisions.includes(revisionId),'SCORER_OR_REVISION_DISABLED');check(run.forecast.status==='valid'&&revision.result.windows.h24.status==='mature'&&revision.result.windows.h24.observed_count===96,'CASE_NOT_COMPLETE');const frozen=await readFrozen(path.join(dataRoot,'forecast-runs',runId));return{run,revision,frozen,scorer};}
 async function content(runId,revisionId){const{run,revision,frozen,scorer}=await verifiedSource(runId,revisionId),f=run.forecast,w=revision.result.windows.h24,raw=f.calibration?.raw_probabilities??f.scenarios.map(s=>s.probability_24h),final=f.scenarios.map(s=>s.probability_24h),main=mainScenario(final),rawMain=mainScenario(raw);
  return{schema:'MFV:M1_CASE:v1',id:digest(runId+':'+revisionId),run_id:runId,revision_id:revisionId,revision_hash:revision.evaluation_sha256,forecast_hash:run.hashes.forecast_sha256,scorer,eligible:true,features:frozen.input.features,raw_probabilities:raw,final_probabilities:final,main_scenario:main,raw_main_scenario:rawMain,actual_category:w.actual_category,path_loss:w.scenario_errors.find(x=>x.id===main).mae_return_pct,raw_path_loss:w.scenario_errors.find(x=>x.id===rawMain).mae_return_pct,all_path_losses:w.scenario_errors,constant_reference:w.constant_baseline,brier:w.brier_score,opportunity_id:`${run.history.instrument}:900:86400:${f.anchor_time}`,start_time:f.anchor_time,end_time:f.anchor_time+86400,frozen_at:f.information_frozen_at,predictor_identity:frozen.input.model_context?.learning?.predictor_identity??{version:'legacy',method:f.method_version},frozen_base:frozen.input.model_context?.learning?.base??null,diagnostics:[],source_evaluated_at:revision.result.evaluated_at};
 }
 async function create(runId,revisionId){const value=await content(runId,revisionId),dir=path.join(home,value.id),file=path.join(dir,'case.json'),commit=path.join(dir,'commit.json');if(await exists(commit))return read(value.id);if(!await exists(file))await writeOnce(dataRoot,file,value);else check(canonical(await readJson(dataRoot,file))===canonical(value),'PARTIAL_CASE_CHANGED');const available_at=new Date().toISOString();check(Date.parse(available_at)>=Date.parse(value.source_evaluated_at),'CASE_SOURCE_FROM_FUTURE');await writeOnce(dataRoot,commit,{schema:'MFV:CASE_COMMIT:v1',id:value.id,sha256:digest(await readBytes(dataRoot,file)),available_at});return read(value.id);}
 async function read(id){check(/^[a-f0-9]{64}$/.test(id),'CASE_ID_INVALID');const dir=path.join(home,id),marker=await readJson(dataRoot,path.join(dir,'commit.json')),bytes=await readBytes(dataRoot,path.join(dir,'case.json'));check(marker.id===id&&digest(bytes)===marker.sha256,'CASE_HASH_MISMATCH');const value=JSON.parse(bytes);check(Number.isFinite(Date.parse(marker.available_at))&&Date.parse(marker.available_at)>=Date.parse(value.source_evaluated_at),'CASE_AVAILABILITY_INVALID');const recomputed=await content(value.run_id,value.revision_id);check(canonical(value)===canonical(recomputed),'CASE_RECOMPUTE_MISMATCH');return{...value,available_at:marker.available_at};}
 async function available(cutoff){const result=[];for(const id of await fs.readdir(home).catch(e=>{if(e.code==='ENOENT')return[];throw e;})){if(!/^[a-f0-9]{64}$/.test(id))continue;const commit=path.join(home,id,'commit.json');if(!await exists(commit))continue;const marker=await readJson(dataRoot,commit);if(Date.parse(marker.available_at)>Date.parse(cutoff))continue;try{result.push(await read(id));}catch{/* Invalid/revoked case is never consumed. Original files remain intact. */}}return result;}
 async function freeze(features,cutoff,policy){const control=await controls(),cases=await available(cutoff),predictor_identity={predictor_version:policy.predictor_version,model:policy.model,reasoning_effort:policy.reasoning_effort,additional_inputs:policy.additional_inputs,feedback:control.learning_disabled?'F0':policy.feedback};const base=baseRate(cases,cutoff),packet=feedback(cases,features,cutoff);return{schema:'MFV:LEARNING_INPUT:v1',predictor_identity,feedback_mode:control.learning_disabled?'F0':policy.feedback,lambda:control.learning_disabled?0:policy.lambda,base,feedback:control.learning_disabled||policy.feedback==='F0'?null:packet,control_effective_at:control.effective_at??null};}
 async function recordFirstDisabledRun(runId){const control=await controls();if(control.learning_disabled&&!control.first_run_id){check(typeof runId==='string'&&runId.startsWith('m1-'),'RUN_ID_INVALID');await atomic(dataRoot,path.join(dataRoot,'m1-learning/controls.json'),{...control,first_run_id:runId});}}
 return{create,read,available,freeze,controls,recordFirstDisabledRun};
}
