import fs from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{validateInstallation,readJson,writeOnce,atomic,check,exists}from'./m1-files.mjs';import{verifyPackage}from'./m1-package.mjs';import{serve}from'./m1-server.mjs';import{cycle}from'./m1-cycle.mjs';import{prepareForecast}from'./m1-input.mjs';import{generateInstalled,generateCandidate}from'./m1-model.mjs';import{createDisplayReader}from'./m1-display.mjs';import{projectionStore}from'./m1-index.mjs';import{ops}from'./m1-ops.mjs';import{backup,restore}from'./m1-backup.mjs';import{caseStore}from'./m1-cases.mjs';import{collectCalendar,collectDerivatives}from'./m1-public-data.mjs';import{experimentStore,effectivePolicy}from'./m1-experiments.mjs';import{supplementary}from'./m1-supplementary.mjs';import{startService,serviceStatus}from'./m1-service.mjs';
export async function entry(command,home,releaseId){
 const codeRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),config=await validateInstallation(path.join(home,'installation.local.json'));process.env.MFV_DATA_ROOT=config.data_root;process.env.MFV_RUNTIME_HOME=home;
 const manifest=await verifyPackage(codeRoot);check(manifest.release_id===releaseId,'PINNED_RELEASE_MISMATCH');
 const policy=await effectivePolicy(config.data_root,manifest.policy.policy);
 const approval=await readJson(home,path.join(home,'approvals',releaseId+'.json'));check(manifest.synthetic!==true&&approval.schema==='MFV:MAINTAINER_APPROVAL:v1'&&approval.release_id===releaseId&&approval.build_sha===manifest.build_sha&&approval.approved===true&&/^https:\/\/github\.com\/He1met\/market-forecast-viewer\/(?:pull|issues)\//.test(approval.source_url)&&Number.isFinite(Date.parse(approval.approved_at)),'RELEASE_NOT_APPROVED');
 if(command==='doctor')return{schema:'MFV:DOCTOR:v1',release_id:releaseId,build_sha:manifest.build_sha,package_integrity:'verified',roots:'separate',production_paused:config.forecast_paused!==false,outer_hard_timeout_verified:false};
 if(command==='serve')return serve({codeRoot,dataRoot:config.data_root,port:config.http_port,paused:config.forecast_paused!==false});
 if(command==='ops'){const service=await serviceStatus({runtimeHome:home,port:config.http_port});if(service.status==='exited'&&config.service_paused===false)await startService({runtimeHome:home,port:config.http_port,releaseId,paused:false,automatic:true});return ops({codeRoot,dataRoot:config.data_root,port:config.mutex_port,releaseId,policy:policy,paused:config.ops_paused!==false,refreshInputs:async({signal})=>{await collectDerivatives(config.data_root,{signal});await collectCalendar(config.data_root,{signal});}});}
 if(command==='backup'){
  const localDay=new Date(Date.now()+8*3600000),date=localDay.toISOString().slice(0,10),result=await backup({dataRoot:config.data_root,runtimeHome:home,target:config.backup.target,deviceId:config.backup.device_id,minimumFreeBytes:config.backup.minimum_free_bytes,port:config.mutex_port,releaseId,slotKey:'daily:'+date});
  if(result.status!=='completed')return result;
  const checksRoot=path.join(config.backup.target,'restore-checks');await fs.mkdir(checksRoot,{recursive:true});
  const pending=path.join(checksRoot,'pending.json');let checkState=await exists(pending)?await readJson(config.backup.target,pending):null;
  if(!checkState&&localDay.getUTCDay()===0){checkState={backup_id:result.manifest.id};await writeOnce(config.backup.target,pending,checkState);}
  if(checkState){const destination=path.join(checksRoot,checkState.backup_id),restored=await restore({target:config.backup.target,manifestFile:path.join(config.backup.target,'manifests',checkState.backup_id+'.json'),destination,resume:await exists(destination),maxMs:90000,maxFiles:2000,verify:async restoredRoot=>{
   const old=process.env.MFV_DATA_ROOT;process.env.MFV_DATA_ROOT=restoredRoot;try{const reader=createDisplayReader({root:codeRoot,dataRoot:restoredRoot}),ids=await reader.listRunIds(),cursorFile=path.join(restoredRoot,'replay-state.json'),state=await exists(cursorFile)?await readJson(restoredRoot,cursorFile):{offset:0,forecasts:[],case_offset:0,cases:[]},started=performance.now();let visited=0;
   for(;state.offset<ids.length;state.offset++){if(visited>=16||performance.now()-started>15000){await atomic(restoredRoot,cursorFile,state);return{status:'incomplete',forecast_cursor:state.offset};}const item=await reader.runState(ids[state.offset],new Date().toISOString());check(item.status!=='invalid','RESTORE_ARCHIVE_INVALID');if(item.status==='valid'||item.status==='late'){const run=await reader.readRun(item.run_id);check(run.evaluation.status!=='failed','RESTORE_EVALUATION_INVALID');state.forecasts.push({run_id:item.run_id,forecast_sha256:run.hashes.forecast_sha256});}visited++;await atomic(restoredRoot,cursorFile,{...state,offset:state.offset+1});}
   const cases=caseStore({codeRoot,dataRoot:restoredRoot}),caseIds=(await fs.readdir(path.join(restoredRoot,'m1-cases')).catch(e=>{if(e.code==='ENOENT')return[];throw e;})).filter(x=>/^[a-f0-9]{64}$/.test(x)).sort();
   for(;state.case_offset<caseIds.length;state.case_offset++){if(visited>=16||performance.now()-started>15000){await atomic(restoredRoot,cursorFile,state);return{status:'incomplete',case_cursor:state.case_offset};}try{const item=await cases.read(caseIds[state.case_offset]);state.cases.push(item.id);}catch(e){check(e.message==='SCORER_OR_REVISION_DISABLED','RESTORE_CASE_INVALID');}visited++;await atomic(restoredRoot,cursorFile,{...state,case_offset:state.case_offset+1});}
   await projectionStore(restoredRoot).update(reader,{limit:16,deadline:performance.now()+15000});return{passed:true,forecast_count:state.forecasts.length,forecasts:state.forecasts,case_count:state.cases.length};}finally{process.env.MFV_DATA_ROOT=old;}
  }});if(restored.schema==='MFV:RESTORE:v1'){await fs.unlink(pending);}return{...result,restore_check:restored};}return result;
 }
 check(command==='forecast','COMMAND_INVALID');return cycle({dataRoot:config.data_root,releaseId,mutexPort:config.mutex_port,paused:config.forecast_paused!==false,trigger:process.env.MFV_TRIGGER??'manual',
 freeze:async({slot,signal,deadline})=>{const events=path.join(config.data_root,'m1-calendar','market-only-'+slot.slot_id+'.json');if(!await exists(events))await writeOnce(config.data_root,events,{schema:'MFV:M1_EVENTS:v1',mode:'market_only',information_cutoff:new Date().toISOString(),sources:[],items:[],limitations:['未纳入事件风险']});return prepareForecast(events,{anchorTime:slot.anchor_time,signal,deadline,supplementaryBuilder:args=>supplementary(config.data_root,{...args,policy:policy}),learningBuilder:(features,cutoff)=>caseStore({codeRoot,dataRoot:config.data_root}).freeze(features,cutoff,policy)});},
 registerOpportunity:async(slot,options)=>(await caseStore({codeRoot,dataRoot:config.data_root}).controls()).learning_disabled?null:experimentStore(config.data_root).register(slot,policy,options),
 prepareCandidate:(registration,input,options)=>experimentStore(config.data_root).freezeCandidate(registration,input,{...options,learningBuilder:(features,cutoff,policy)=>caseStore({codeRoot,dataRoot:config.data_root}).freeze(features,cutoff,policy)}),
 runCandidate:generateCandidate,finishOpportunity:(registration,result)=>experimentStore(config.data_root).finish(registration,result),
 generate:async(prepared,options)=>{await caseStore({codeRoot,dataRoot:config.data_root}).recordFirstDisabledRun(prepared.run_id);return generateInstalled(prepared,options);},publishIndex:({mutex,deadline})=>projectionStore(config.data_root).update(createDisplayReader({root:codeRoot,dataRoot:config.data_root}),{limit:16,guard:mutex.guard,deadline})});
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){entry(process.argv[2],process.argv[3],process.argv[4]).then(result=>{if(process.argv[2]!=='serve')console.log(JSON.stringify(result));}).catch(e=>{console.error(e.message);process.exitCode=1;});}
