import fs from 'node:fs/promises';import path from 'node:path';import{fileURLToPath}from'node:url';import{createHash,randomUUID}from'node:crypto';
export const digest=x=>createHash('sha256').update(x).digest('hex');
export const encode=x=>JSON.stringify(x,null,2)+'\n';
export const canonical=x=>JSON.stringify(sort(x));function sort(x){return Array.isArray(x)?x.map(sort):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):x;}
export const check=(x,code)=>{if(!x)throw Error(code);};
export function within(root,file){const r=path.relative(path.resolve(root),path.resolve(file));return !r.startsWith('..'+path.sep)&&r!=='..'&&!path.isAbsolute(r);}
export async function safePath(root,file,{missing=false}={}){root=path.resolve(root);file=path.resolve(file);check(within(root,file),'PATH_ESCAPE');check(await fs.realpath(root)===root,'ROOT_SYMLINK_FORBIDDEN');let p=root;for(const bit of ['.',...path.relative(root,file).split(path.sep).filter(Boolean)]){p=path.resolve(p,bit);try{check(!(await fs.lstat(p)).isSymbolicLink(),'SYMLINK_FORBIDDEN');}catch(e){if(e.code==='ENOENT'&&missing)return file;throw e;}}check(await fs.realpath(root)===root,'ROOT_SYMLINK_FORBIDDEN');return file;}
export async function readBytes(root,file,max=32*1024*1024){await safePath(root,file);const stat=await fs.stat(file);check(stat.isFile()&&stat.size<=max,'FILE_SIZE_OR_TYPE');return fs.readFile(file);}
export const readJson=async(root,file)=>JSON.parse((await readBytes(root,file)).toString('utf8'));
export async function writeOnce(root,file,value){await safePath(root,file,{missing:true});await fs.mkdir(path.dirname(file),{recursive:true,mode:0o700});await safePath(root,path.dirname(file));await fs.writeFile(file,typeof value==='string'||Buffer.isBuffer(value)?value:encode(value),{flag:'wx',mode:0o600});}
export async function atomic(root,file,value){const tmp=file+'.'+randomUUID()+'.tmp';await writeOnce(root,tmp,value);await fs.rename(tmp,file);}
export async function exists(file){try{await fs.lstat(file);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}}
export const sourceCodeRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export function dataReference(ref,dataRoot){check(typeof ref==='string'&&!path.isAbsolute(ref)&&!ref.includes('\\')&&!ref.split('/').includes('..'),'DATA_REFERENCE_INVALID');const rel=ref.startsWith('artifacts/')?ref.slice(10):ref;check(rel&&!rel.startsWith('artifacts/'),'DOUBLE_ARTIFACTS_PREFIX');const full=path.resolve(dataRoot,rel);check(within(dataRoot,full),'DATA_REFERENCE_ESCAPE');return full;}
export function configuredRoots(){const code_root=sourceCodeRoot,data_root=path.resolve(process.env.MFV_DATA_ROOT??path.join(code_root,'artifacts')),runtime_home=path.resolve(process.env.MFV_RUNTIME_HOME??path.join(code_root,'.local/runtime'));return{code_root,data_root,runtime_home};}
export async function validateInstallation(file){const home=path.dirname(path.resolve(file));const c=await readJson(home,path.resolve(file));check(c.schema==='MFV:INSTALLATION:v1','INSTALLATION_INVALID');for(const key of ['data_root','runtime_home']){check(path.isAbsolute(c[key]),'ABSOLUTE_ROOT_REQUIRED');check(await fs.realpath(c[key])===c[key],'ROOT_SYMLINK_FORBIDDEN');}check(c.runtime_home===home&&!within(c.data_root,c.runtime_home)&&!within(c.runtime_home,c.data_root),'ROOTS_NOT_SEPARATE');for(const p of ['http_port','mutex_port'])check(Number.isInteger(c[p])&&c[p]>=1024&&c[p]<=65535,'INVALID_PORT');check(c.http_port!==c.mutex_port,'PORTS_MUST_DIFFER');return c;}
