import path from'node:path';import{randomUUID}from'node:crypto';import{writeOnce,atomic,readJson,exists,check}from'./m1-files.mjs';import{businessMutex}from'./m1-mutex.mjs';import{createDisplayReader}from'./m1-display.mjs';import{createOutcomeStore}from'./m1-outcome-store.mjs';import{projectionStore}from'./m1-index.mjs';import{caseStore}from'./m1-cases.mjs';import{experimentStore,effectivePolicy}from'./m1-experiments.mjs';import{mainScenario,fitLambda}from'./m1-learning.mjs';import fs from'node:fs/promises';
export async function ops({codeRoot,dataRoot,port,releaseId,policy,paused=false,refreshInputs=async()=>{}}){
 const slotHour=new Date().toISOString().slice(0,13),slotFile=path.join(dataRoot,'m1-control/ops-slots',slotHour.replace(/[^0-9]/g,'')+'.json');
 const start=performance.now(),id=randomUUID(),folder=path.join(dataRoot,'m1-observations',id),observation={schema:'MFV:OBSERVATION:v1',id,task:'ops',release_id:releaseId,started_at:new Date().toISOString()};await writeOnce(dataRoot,path.join(folder,'started.json'),observation);let mutex,result={status:'failed',reason:'incomplete'};
 try{if(paused){result={status:'skipped',reason:'paused'};return result;}mutex=await businessMutex({dataRoot,port,releaseId,task:'ops'});if(mutex.status!=='ACQUIRED'){result={status:'skipped',reason:mutex.status};return result;}
  if(await exists(slotFile)&&(await readJson(dataRoot,slotFile)).status==='completed'){result={status:'skipped',reason:'slot_completed'};return result;}
  await atomic(dataRoot,slotFile,{schema:'MFV:OPS_SLOT:v1',slot_hour:slotHour,status:'running',observation_id:id,started_at:observation.started_at});
  const guard=async()=>{await mutex.guard();check(performance.now()-start<120000,'OPS_WRITE_DEADLINE');};
  const experiment=experimentStore(dataRoot);const recoveredDecision=await experiment.recoverTransition({guard});
  const readers={production:createDisplayReader({root:codeRoot,dataRoot}),candidate:createDisplayReader({root:codeRoot,dataRoot,runsRoot:path.join(dataRoot,'m1-candidates')})};
  const outcomes=[];let processed=0;
  for(const role of ['production','candidate']){const reader=readers[role],runsRoot=path.join(dataRoot,role==='production'?'forecast-runs':'m1-candidates'),store=createOutcomeStore({root:codeRoot,dataRoot,runsRoot}),ids=await reader.listRunIds();const cursorFile=path.join(dataRoot,'m1-control/ops-'+role+'-cursor.json'),cursor=await exists(cursorFile)?await readJson(dataRoot,cursorFile):{offset:0};const offset=ids.length?cursor.offset%ids.length:0,ordered=[...ids.slice(offset),...ids.slice(0,offset)];let visited=0;
   for(const runId of ordered){if(processed>=16||visited>=8||performance.now()-start>85000)break;await guard();processed++;visited++;try{const run=await reader.readRun(runId);if(run.forecast.status!=='valid')continue;if(run.evaluation.status==='available'&&run.evaluation.result.windows.h24.status==='mature'){if(role==='production')await caseStore({codeRoot,dataRoot}).create(run.run_id,run.evaluation.revision_id);continue;}const capture=await store.capture(run,{signal:AbortSignal.timeout(Math.max(1,Math.floor(115000-(performance.now()-start)))),deadline:start+115000});if(capture.status==='ok'){await guard();const revision=await store.evaluateCapture(run,capture.capture_id);if(role==='production'&&revision.result.windows.h24.status==='mature')await caseStore({codeRoot,dataRoot}).create(run.run_id,revision.revision_id);}outcomes.push({role,run_id:runId,...capture});}catch(e){outcomes.push({role,run_id:runId,status:'failed',reason:e.message});}}
   if(visited){await guard();await atomic(dataRoot,cursorFile,{offset:offset+visited});}
  }
  let decision=recoveredDecision;
  if(performance.now()-start<100000){await guard();decision=recoveredDecision??((await caseStore({codeRoot,dataRoot}).controls()).learning_disabled?{decision:'paused_learning_disabled'}:await experiment.review({guard,readMetrics:async(id,role)=>{try{const run=await readers[role].readRun(id),f=run.forecast,e=run.evaluation.status==='available'?run.evaluation.result.windows.h24:null,main=mainScenario(f.scenarios.map(x=>x.probability_24h));return{valid:f.status==='valid',timely:Date.parse(f.published_at)<(f.anchor_time+900)*1000,started_at:f.generation_started_at,complete:e?.status==='mature',brier:e?.brier_score??null,path_loss:e?.scenario_errors.find(x=>x.id===main).mae_return_pct??null};}catch{return null;}}}));
   if(policy)policy=await effectivePolicy(dataRoot,policy);
   if(policy&&!await experiment.active()){
    const control=await caseStore({codeRoot,dataRoot}).controls();
    if(!control.learning_disabled){const cutoff=new Date().toISOString(),cases=await caseStore({codeRoot,dataRoot}).available(cutoff),used=new Set();
     for(const id of await fs.readdir(path.join(dataRoot,'m1-experiments')).catch(e=>{if(e.code==='ENOENT')return[];throw e;})){if(!/^[a-f0-9-]{36}$/.test(id))continue;const file=path.join(dataRoot,'m1-experiments',id,'plan.json');if(await exists(file))used.add((await readJson(dataRoot,file)).factor);}
     if(!used.has('feedback')&&policy.feedback==='F0'&&cases.length>=2)await experiment.create(policy,{...policy,feedback:'F1'},{guard,trainingCutoff:cutoff});
     else if(used.has('feedback')&&!used.has('probability')){const identity={predictor_version:policy.predictor_version,model:policy.model,reasoning_effort:policy.reasoning_effort,additional_inputs:policy.additional_inputs,feedback:policy.feedback},fit=fitLambda(cases,cutoff,identity);if(fit.n>=20&&fit.lambda!==policy.lambda)await experiment.create(policy,{...policy,lambda:fit.lambda},{guard,trainingCutoff:cutoff,factor:'probability',trainingEvidence:fit});}
    }
   }
  }
  if(performance.now()-start<95000)await refreshInputs({signal:AbortSignal.timeout(Math.max(1,Math.floor(115000-(performance.now()-start))))});
  const projection=await projectionStore(dataRoot).update(readers.production,{limit:16,guard,deadline:start+120000});result={status:'completed',outcomes,projection,decision};await guard();await atomic(dataRoot,slotFile,{schema:'MFV:OPS_SLOT:v1',slot_hour:slotHour,status:'completed',observation_id:id,completed_at:new Date().toISOString()});return result;
 }catch(e){result={status:'failed',reason:e.message};return result;}finally{const final={...observation,...result,completed_at:new Date().toISOString(),elapsed_ms:performance.now()-start};await writeOnce(dataRoot,path.join(folder,'result.json'),final);if(mutex?.status==='ACQUIRED'){await mutex.guard();await atomic(dataRoot,path.join(dataRoot,'m1-task-status/ops.json'),final);await mutex.close();}}
}
