import{createChart,CandlestickSeries,LineSeries,CrosshairMode,LineStyle,ColorType,PriceScaleMode,type IPriceLine,type IChartApi,type ISeriesApi,type Time,type UTCTimestamp}from'lightweight-charts';
import{ForecastBand}from'./forecast-band';
import type{Scheme}from'./contracts';
import{chartPriceRange,chartSupportPoints,isExperimentForecast,validateActualPoints,type ActualChartPoint,type ChartHistory,type ChartForecast}from'./chart-model';
export const utc=(t:number)=>t as UTCTimestamp;
const lifetime={created:0,destroyed:0,subscriptions:0};
export const colors=['#f0bd6c','#8cb8ff','#70ddbc','#ef90b2','#b4a0f3','#c8d4dd'];
export class WeatherChart {
 readonly chart:IChartApi;readonly candles:ISeriesApi<'Candlestick'>;readonly support?:ISeriesApi<'Line'>;
 readonly h:ChartHistory;readonly f?:ChartForecast;zone=Intl.DateTimeFormat().resolvedOptions().timeZone;hours=24;
 private gridLines:IPriceLine[]=[];private scheme?:Scheme;private disposed=false;
 readonly paths=new Map<string,ISeriesApi<'Line'>>();band?:ForecastBand;
 private actual?:ISeriesApi<'Line'>;private actualPoints:ActualChartPoint[]=[];
 private hover:(t:number|undefined)=>void;
 constructor(container:HTMLElement,h:ChartHistory,f:ChartForecast|undefined,onHover:(t:number|undefined)=>void){lifetime.created++;this.h=h;this.f=f;this.chart=createChart(container,{autoSize:true,layout:{background:{type:ColorType.Solid,color:'#111d2c'},textColor:'#94a7bc',fontFamily:'-apple-system, BlinkMacSystemFont, sans-serif',fontSize:11,attributionLogo:true},grid:{vertLines:{color:'#213043'},horzLines:{color:'#213043'}},crosshair:{mode:CrosshairMode.Normal,vertLine:{color:'#9eafc5'},horzLine:{color:'#9eafc5'}},rightPriceScale:{mode:PriceScaleMode.Normal,borderColor:'#334357',scaleMargins:{top:.16,bottom:.12}},timeScale:{timeVisible:true,secondsVisible:false,borderColor:'#334357',rightOffset:3},handleScroll:true,handleScale:true});
 this.candles=this.chart.addSeries(CandlestickSeries,{priceScaleId:'right',upColor:'#56bea6',downColor:'#eb8290',wickUpColor:'#56bea6',wickDownColor:'#eb8290',borderVisible:false,priceLineVisible:false,lastValueVisible:false});this.candles.setData(h.candles.map(c=>({time:utc(c.open_time),open:c.open,high:c.high,low:c.low,close:c.close})));
 if(f){this.support=this.chart.addSeries(LineSeries,{priceScaleId:'right',visible:true,lineVisible:false,pointMarkersVisible:false,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false,lastPriceAnimation:0,autoscaleInfoProvider:()=>({priceRange:this.autoscale()})});this.support.setData(chartSupportPoints(h,f).map(point=>({...point,time:utc(point.time)})));}
 if(f&&this.support){f.scenarios.forEach((s,i)=>{const line=this.chart.addSeries(LineSeries,{priceScaleId:'right',color:colors[i%colors.length],lineWidth:2,lineStyle:([LineStyle.Solid,LineStyle.Dashed,LineStyle.SparseDotted])[i%3],lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false});line.setData([{time:utc(f.anchor_time),value:f.anchor_price},...s.points.map(p=>({time:utc(p.time),value:p.price}))]);this.paths.set(s.id,line);});this.band=new ForecastBand(this.chart,this.support,f);this.support.attachPrimitive(this.band);}
 this.hover=t=>onHover(t);this.chart.subscribeCrosshairMove(this.onCrosshair);lifetime.subscriptions++;this.setTimezone(this.zone);this.reset();
 }
 private onCrosshair=(p:{time?:unknown})=>this.hover(typeof p.time==='number'?p.time:undefined);
 protected autoscale(){const range=this.chart.timeScale().getVisibleRange();return chartPriceRange(this.h,this.f,range?Number(range.from):this.h.start_time,range?Number(range.to):Infinity,new Set([...this.paths].filter(([,series])=>series.options().visible).map(([id])=>id)),this.scheme,this.actualPoints);}
 setGrid(scheme?:Scheme){if(!this.support)return;for(const line of this.gridLines)this.support.removePriceLine(line);this.gridLines=[];if(this.f&&isExperimentForecast(this.f))scheme=undefined;this.scheme=scheme;if(scheme)this.gridLines=scheme.levels.map((price,i)=>this.support!.createPriceLine({price,color:i===0||i===scheme.interval_count?'#c49b60':'rgba(196,155,96,0.48)',lineWidth:1,lineStyle:LineStyle.Dotted,axisLabelVisible:i===0||i===scheme.interval_count,title:i===0?'DEMO下界':i===scheme.interval_count?'DEMO上界':''}));this.support.applyOptions({autoscaleInfoProvider:()=>({priceRange:this.autoscale()})});}
 setActual(points:readonly ActualChartPoint[]=[]){const checked=validateActualPoints(this.f,points);if(!checked.length){if(this.actual)this.chart.removeSeries(this.actual);this.actual=undefined;this.actualPoints=[];}else{if(!this.actual)this.actual=this.chart.addSeries(LineSeries,{priceScaleId:'right',color:'#ffffff',lineWidth:2,lineStyle:LineStyle.Dotted,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false});this.actual.setData([{time:utc(this.f!.anchor_time),value:this.f!.anchor_price},...checked.map(point=>({time:utc(point.time),value:point.price}))]);this.actualPoints=checked;}this.support?.applyOptions({autoscaleInfoProvider:()=>({priceRange:this.autoscale()})});}
 setWindow(hours:number){this.hours=hours;this.reset();}
 setPath(id:string,visible:boolean){this.paths.get(id)?.applyOptions({visible});this.support?.applyOptions({autoscaleInfoProvider:()=>({priceRange:this.autoscale()})});}

 format(t:number,full=false){return new Intl.DateTimeFormat('zh-CN',{timeZone:this.zone,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,...full?{year:'numeric'}:{}}).format(new Date(t*1000));}
 setTimezone(zone:string){this.zone=zone;this.chart.applyOptions({localization:{timeFormatter:(t:Time)=>this.format(Number(t),true)},timeScale:{tickMarkFormatter:(t:Time)=>this.format(Number(t))}});}
 reset(){this.chart.priceScale('right').applyOptions({autoScale:true});const end=this.f?this.f.anchor_time+this.hours*3600:this.h.end_time-900;this.chart.timeScale().setVisibleRange({from:utc(this.h.end_time-48*3600),to:utc(end)});}
 setRange(from:number,to:number){this.chart.timeScale().setVisibleRange({from:utc(from),to:utc(to)});}
 diagnostics(){const f=this.f;return{historyCount:this.candles.data().length,historyLastTime:Number(this.candles.data().at(-1)?.time),supportCount:this.support?.data().length??0,range:this.chart.timeScale().getVisibleLogicalRange(),visibleTime:this.chart.timeScale().getVisibleRange(),priceWidth:this.chart.priceScale('right').width(),anchor:f?.anchor_time,futureEnd:f?f.anchor_time+f.horizon_seconds:undefined,anchorX:f?this.chart.timeScale().timeToCoordinate(utc(f.anchor_time)):null,priceY:f?this.support?.priceToCoordinate(f.anchor_price):null,priceY2:f?this.support?.priceToCoordinate(f.anchor_price*1.01):null,canvasCount:document.querySelectorAll('#chart canvas').length,subscriptions:lifetime.subscriptions,activeCharts:lifetime.created-lifetime.destroyed,createdCharts:lifetime.created,destroyedCharts:lifetime.destroyed,gridLineCount:this.support?.priceLines().length??0,gridPrices:this.support?.priceLines().map(p=>p.options().price)??[],schemeId:this.scheme?.id,hours:this.hours,pathCount:this.paths.size,visiblePaths:[...this.paths].filter(([,s])=>s.options().visible).map(([id])=>id),bandDraws:this.band?.drawCount??0,vertices:this.band?.rendered??[],coordinateCheck:f&&!isExperimentForecast(f)?f.bands.points.map(b=>({time:b.time,x:this.chart.timeScale().timeToCoordinate(utc(b.time)),outerUpper:this.support?.priceToCoordinate(b.outer_upper),candleY:this.candles.priceToCoordinate(b.inner_upper),supportY:this.support?.priceToCoordinate(b.inner_upper)})):[],mode:f&&isExperimentForecast(f)?'experiment':'demo',rangeKind:f?.bands.kind,stageRendered:this.band?.stageRendered??[],stageCoordinateCheck:f&&isExperimentForecast(f)?f.stages.map(stage=>({id:stage.id,startX:this.chart.timeScale().timeToCoordinate(utc(stage.start_time)),endX:this.chart.timeScale().timeToCoordinate(utc(stage.end_time)),lowerY:this.support?.priceToCoordinate(stage.lower),upperY:this.support?.priceToCoordinate(stage.upper),supportY:this.support?.priceToCoordinate(stage.upper),candleY:this.candles.priceToCoordinate(stage.upper)})):[],actualCount:this.actualPoints.length,actualPoints:this.actualPoints.map(point=>({...point})),actualCoordinates:this.actualPoints.map(point=>({...point,x:this.chart.timeScale().timeToCoordinate(utc(point.time)),y:this.actual?.priceToCoordinate(point.price),supportY:this.support?.priceToCoordinate(point.price)}))};}
 destroy(){if(this.disposed)return;this.disposed=true;this.setGrid(undefined);if(this.band&&this.support)this.support.detachPrimitive(this.band);this.paths.clear();this.chart.unsubscribeCrosshairMove(this.onCrosshair);this.chart.remove();lifetime.destroyed++;lifetime.subscriptions--;}
}
