import { z } from 'zod';
const str = z.string().min(1), int = z.number().int().safe().nonnegative(), price = z.number().finite().positive();
const iso = z.string().datetime({ offset: false }), hash = z.string().regex(/^[a-f0-9]{64}$/);
const obj = <T extends z.ZodRawShape>(s:T) => z.object(s).strict();
const common = {schema_version:z.literal('1.0.0'), content_sha256:hash, instrument:z.literal('BTC-USDT-SWAP'),market_type:z.literal('linear_perpetual'),price_type:z.literal('trade'),time_unit:z.literal('s'),bar_seconds:z.literal(900)};
const params=obj({instId:z.literal('BTC-USDT-SWAP'),bar:z.literal('15m'),limit:z.literal(300),after:z.string().regex(/^\d+$/).optional(),before:z.string().regex(/^\d+$/).optional()});
export const candleSchema=obj({open_time:int,close_time:int,open:price,high:price,low:price,close:price,volume_contracts:z.number().finite().nonnegative(),volume_base:z.number().finite().nonnegative(),volume_quote:z.number().finite().nonnegative(),closed:z.literal(true)});
const historySchema=obj({...common,kind:z.literal('history'),dataset_id:str,base_currency:z.literal('BTC'),quote_currency:z.literal('USDT'),settle_currency:z.literal('USDT'),timezone:z.literal('UTC'),downloaded_at:iso,start_time:int,end_time:int,count:z.literal(1344),quality:obj({excluded_unclosed_count:int,identical_duplicates_removed:int,gaps:z.array(z.never()),conflicting_duplicates:z.array(z.never())}),source:obj({provider:z.literal('OKX'),endpoint:z.literal('https://www.okx.com/api/v5/market/history-candles'),documentation_url:z.string().url(),request:obj({instId:z.literal('BTC-USDT-SWAP'),bar:z.literal('15m'),limit:z.literal(300),requested_start_time:int,requested_end_time:int}),raw_responses:z.array(obj({path:z.string().regex(/^artifacts\/data-source\/[a-zA-Z0-9_-]+\/page-\d+\.json$/),sha256:hash,requested_at:iso,params,response_code:z.literal('0')})).min(1)}),candles:z.array(candleSchema).length(1344)});
const demo={...common,demo:z.literal(true),source_kind:z.literal('synthetic_fixture'),history_dataset_id:str,history_content_sha256:hash,generator_version:str,seed:int.max(4294967295),generated_at:iso,anchor_time:int,anchor_price:price,horizon_seconds:int.positive(),step_seconds:int.positive()};
const forecastSchema=obj({...demo,kind:z.literal('forecast_demo'),forecast_id:str,label:z.literal('DEMO 演示未来，非交易信号'),future_count:int.positive(),stages:z.array(obj({id:str,name:str,start_time:int,end_time:int})).min(1),scenarios:z.array(obj({id:str,name:str,description:str,points:z.array(obj({time:int,price}))})).min(3),bands:obj({kind:z.literal('illustrative'),label:z.literal('示意区间，未经校准'),points:z.array(obj({time:int,inner_lower:price,inner_upper:price,outer_lower:price,outer_upper:price}))})});
const schemeSchema=obj({id:str,name:str,mode:obj({id:str,label:str}),initial_position_label:str.optional(),lower_price:price,upper_price:price,distribution:z.enum(['arithmetic','geometric']),interval_count:int.positive(),levels:z.array(price)});
const gridsSchema=obj({...demo,kind:z.literal('grids_demo'),grid_set_id:str,label:z.literal('DEMO 网格配置，未接入收益评估'),default_scheme_id:str,schemes:z.array(schemeSchema).min(3)});
export type History=z.infer<typeof historySchema>;export type Forecast=z.infer<typeof forecastSchema>;export type Grids=z.infer<typeof gridsSchema>;export type Scheme=z.infer<typeof schemeSchema>;
export type Candle=z.infer<typeof candleSchema>;
export function check(ok:unknown,message:string):asserts ok {if(!ok)throw new Error(message);}
// A small strict JSON grammar walk catches duplicate decoded keys before JSON.parse.
export function parseStrict(text:string):unknown {
 let p=0;const ws=()=>{while(/\s/.test(text[p]??'')&&p<text.length)p++;};
 const string=():string=>{const start=p++;while(p<text.length){if(text[p]==='\\'){p+=2;continue;}if(text[p++]==='"')return JSON.parse(text.slice(start,p));}throw Error('JSON 字符串未结束');};
 const value=():void=>{ws();if(text[p]==='{'){p++;ws();const keys=new Set<string>();if(text[p]==='}'){p++;return;}while(p<text.length){ws();check(text[p]==='"','JSON 对象键错误');const key=string();check(!keys.has(key),`重复 JSON 键：${key}`);keys.add(key);ws();check(text[p++]===':','JSON 缺少冒号');value();ws();const end=text[p++];if(end==='}')return;check(end===',','JSON 对象格式错误');}throw Error('JSON 对象未结束');}if(text[p]==='['){p++;ws();if(text[p]===']'){p++;return;}while(p<text.length){value();ws();const end=text[p++];if(end===']')return;check(end===',','JSON 数组格式错误');}throw Error('JSON 数组未结束');}if(text[p]==='"'){string();return;}const m=text.slice(p).match(/^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/);check(m,'JSON 值错误');p+=m[0].length;};
 value();ws();check(p===text.length,'JSON 尾部无效');return JSON.parse(text);
}
export function canonical(value:unknown):string {if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical((value as Record<string,unknown>)[k])).join(',')+'}';if(typeof value==='number')check(Number.isFinite(value),'非法非有限数字');return JSON.stringify(value);}
export async function sha256(bytes:Uint8Array|string):Promise<string>{const b=typeof bytes==='string'?new TextEncoder().encode(bytes):bytes;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(b)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
const identities={history:['dataset_id','history:'],forecast_demo:['forecast_id','forecast-demo:'],grids_demo:['grid_set_id','grids-demo:']} as const;
export async function seal<T extends Record<string,unknown>>(input:T):Promise<T>{const out={...input};const identity=identities[out.kind as keyof typeof identities];check(identity,'不支持文件类型');delete out.content_sha256;delete out[identity[0]];const digest=await sha256(canonical(out));return {...out,content_sha256:digest,[identity[0]]:identity[1]+digest};}
async function integrity(data:Record<string,unknown>){const sealed=await seal(data);const key=identities[data.kind as keyof typeof identities][0];check(sealed.content_sha256===data.content_sha256,'content_sha256 内容不匹配');check(sealed[key]===data[key],`${key} 与内容哈希不匹配`);}
function unique(items:{id:string}[]){check(new Set(items.map(x=>x.id)).size===items.length,'重复 id');}
export async function validateHistory(input:unknown):Promise<History>{const h=historySchema.parse(input);await integrity(h);check(h.start_time===h.candles[0].open_time&&h.end_time===h.candles.at(-1)!.close_time,'历史起止不匹配');check(h.end_time-h.start_time===14*86400,'历史窗口不是14天');check(h.source.request.requested_start_time===h.start_time&&h.source.request.requested_end_time===h.end_time,'请求窗口不匹配');check(h.end_time<=Date.parse(h.downloaded_at)/1000,'历史收盘晚于下载时间');h.candles.forEach((c,i)=>{check(c.open_time%900===0&&c.close_time===c.open_time+900,`candles[${i}] 时间单位/边界错误`);check(i===0||c.open_time===h.candles[i-1].close_time,`candles[${i}] 重复或缺口`);check(c.low<=Math.min(c.open,c.close)&&c.high>=Math.max(c.open,c.close),`candles[${i}] OHLC错误`);});return h;}
function linked(d:Forecast|Grids,h:History){check(d.history_dataset_id===h.dataset_id&&d.history_content_sha256===h.content_sha256,'历史 ID/hash 关联不匹配');check(d.anchor_time===h.end_time&&d.anchor_price===h.candles.at(-1)!.close,'历史收盘锚点不匹配');check(d.generated_at===h.downloaded_at,'固定生成时间错误');check(d.step_seconds===h.bar_seconds&&d.horizon_seconds%d.step_seconds===0,'DEMO步长/窗口错误');}
export async function validateForecast(input:unknown,h:History):Promise<Forecast>{const f=forecastSchema.parse(input);await integrity(f);linked(f,h);check(f.future_count===f.horizon_seconds/f.step_seconds,'未来数量错误');unique(f.scenarios);unique(f.stages);let last=f.anchor_time;for(const s of f.stages){check(s.start_time===last&&s.end_time>s.start_time&&(s.end_time-f.anchor_time)%f.step_seconds===0,'阶段重叠/缺口/对齐错误');last=s.end_time;}check(last===f.anchor_time+f.horizon_seconds,'阶段未覆盖窗口');const nodes=(ps:{time:number}[])=>{check(ps.length===f.future_count,'未来节点数量错误');ps.forEach((p,i)=>check(p.time===f.anchor_time+(i+1)*f.step_seconds,`未来节点[${i}]时间错误`));};f.scenarios.forEach(s=>nodes(s.points));check(new Set(f.scenarios.map(s=>JSON.stringify(s.points))).size===f.scenarios.length,'场景走势重复');nodes(f.bands.points);f.bands.points.forEach((b,i)=>check(b.outer_lower<=b.inner_lower&&b.inner_lower<=b.inner_upper&&b.inner_upper<=b.outer_upper,`区间[${i}]嵌套错误`));return f;}
export async function validateGrids(input:unknown,h:History,f:Forecast):Promise<Grids>{const g=gridsSchema.parse(input);await integrity(g);linked(g,h);check(g.horizon_seconds===f.horizon_seconds&&g.step_seconds===f.step_seconds,'网格窗口不匹配');unique(g.schemes);check(g.schemes.some(s=>s.id===g.default_scheme_id),'默认网格不存在');for(const s of g.schemes){check(s.lower_price<s.upper_price&&s.levels.length===s.interval_count+1,'网格边界/N+1错误');check(s.levels[0]===s.lower_price&&s.levels.at(-1)===s.upper_price,'网格首尾错误');s.levels.forEach((v,i)=>{check(i===0||v>s.levels[i-1],'网格层级不递增');const expected=s.distribution==='arithmetic'?s.lower_price+(s.upper_price-s.lower_price)*i/s.interval_count:s.lower_price*(s.upper_price/s.lower_price)**(i/s.interval_count);check(Math.abs(v-expected)<=Math.max(1e-8,Math.abs(expected)*1e-10),'网格分布不匹配');});}return g;}
