import './styles.css';
import { loadDataset, type Dataset } from './data';
import { WeatherChart, colors } from './chart';
import { gridPosition, generationExplanation } from './demo-explanation';
const $ = (id:string) => document.getElementById(id)!;
let view:WeatherChart|undefined, dataset:Dataset={errors:[]}, request=0, controller:AbortController|undefined;
$('app').innerHTML=`<header><div class="brand"><span class="brand-icon">◒</span><div><h1>市场天气</h1><p>MARKET WEATHER / BTC</p></div></div><div class="demo-badge">DEMO 演示未来｜非交易信号</div><div class="header-note">本地历史快照 <span class="dot"></span></div></header><main><section class="market-head"><div><span class="eyebrow">OKX · USDT 线性永续</span><h2>BTC <span>/ USDT</span> <small>15m</small></h2></div><div id="metadata" class="metadata">正在读取本地数据…</div></section><section class="chart-shell"><div class="toolbar"><div id="legend"></div><div id="controls"><select id="window" aria-label="未来展示窗口"><option value="6">未来 6h</option><option value="12">未来 12h</option><option value="24" selected>未来 24h</option></select><button id="reset">重置视图</button><select id="timezone" aria-label="显示时区"><option value="local">浏览器时区</option><option value="UTC">UTC</option></select><button id="reload">重载文件</button></div></div><div class="demo-context"><p>未来为固定 DEMO 情景路径，不是本轮 Codex 市场预测；区间未经校准。 <strong>概率：未计算（固定 DEMO）</strong></p><details id="generation"><summary>生成依据</summary><div id="generation-content"></div></details></div><div id="chart" role="img" aria-label="BTC真实历史与DEMO未来图表"></div><div class="chart-foot"><span id="hover">移动十字线查看数据</span><span>滚轮缩放 · 拖动平移 · 拖动右轴缩放价格</span></div></section><div id="errors" role="alert" hidden></div><section class="grid-controls"><div class="grid-picker"><label for="scheme">DEMO 网格方案</label><select id="scheme" aria-label="网格方案"></select><label class="grid-visible"><input id="grid-visible" type="checkbox" checked>显示网格</label></div><div><div id="grid-summary"></div><small id="position-label"></small><p id="grid-position"></p></div><details id="levels"><summary>查看价格层级</summary><div id="level-values"></div></details></section><section id="detail" class="detail"><p>内层 / 外层示意区间 · 未经校准 · 路径仅为固定演示模板</p><span id="load-status" role="status">正在读取文件…</span></section><footer><span>数据来源 <a href="https://www.okx.com/docs-v5/en/#order-book-trading-market-data-get-candlesticks-history" target="_blank" rel="noreferrer">OKX 官方公开接口</a> · <span id="dataset-id"></span></span><span>仅作演示 · <a href="/licenses/index.html" target="_blank">第三方声明</a> · <a href="/licenses/lightweight-charts-LICENSE.txt" target="_blank">Apache-2.0</a> · <a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">TradingView</a></span></footer></main>`;
const select=(id:string)=>$(id) as HTMLSelectElement;
function updateMeta(){const h=dataset.history;if(!view||!h){$('metadata').textContent='历史数据不可用';$('dataset-id').textContent='无有效快照';return;}$('metadata').textContent=`历史截止 ${view.format(h.end_time,true)}\n演示锚点 ${dataset.forecast?view.format(dataset.forecast.anchor_time,true):'不可用'} · ${view.zone}`;$('dataset-id').textContent='快照 '+h.dataset_id.slice(8,20);$('dataset-id').title=h.dataset_id;}
function hover(t:number|undefined){if(!view||t===undefined){$('hover').textContent='移动十字线查看真实历史 / DEMO未来数值';return;}const c=dataset.history?.candles.find(c=>c.open_time===t);if(c){$('hover').textContent=`${view.format(t,true)} · 真实历史  O ${c.open}  H ${c.high}  L ${c.low}  C ${c.close}`;return;}const f=dataset.forecast,idx=f?Math.round((t-f.anchor_time)/f.step_seconds)-1:-1,b=f?.bands.points[idx];$('hover').textContent=b&&f?`${view.format(t,true)} · DEMO ${f.scenarios.filter(s=>view!.paths.get(s.id)?.options().visible).map(s=>s.name+' '+s.points[idx].price.toFixed(2)).join(' / ')}\n内带 ${b.inner_lower.toFixed(2)}–${b.inner_upper.toFixed(2)} · 外带 ${b.outer_lower.toFixed(2)}–${b.outer_upper.toFixed(2)} · 未经校准`:`${view.format(t,true)} · 演示锚点，无真实未来 OHLC`;}
function updateGrid(){const scheme=dataset.grids?.schemes.find(s=>s.id===select('scheme').value);view?.setGrid(($('grid-visible')as HTMLInputElement).checked?scheme:undefined);$('grid-summary').textContent=scheme?`${scheme.mode.label} · ${scheme.distribution==='arithmetic'?'等差':'等比'} · ${scheme.lower_price.toFixed(2)}–${scheme.upper_price.toFixed(2)} USDT · ${scheme.interval_count} 区间 / ${scheme.levels.length} 条价格线`:'网格配置不可用';$('level-values').textContent=scheme?scheme.levels.map((p,i)=>`${i}: ${p.toFixed(2)}`).join('　 /　 '):'';$('position-label').textContent=scheme?`方向只是配置标签；未模拟底仓、未生成实际订单。${scheme.initial_position_label??'文件未提供底仓说明。'}`:'底仓说明不可用';const stats=scheme&&dataset.grids?gridPosition(dataset.grids.anchor_price,scheme.levels):undefined;const percent=(n:number)=>`${n>0?'+':''}${n.toFixed(2)}%`;$('grid-position').textContent=stats?`来源：文件中的 DEMO 参数 · 相对锚点：下界 ${percent(stats.lowerPercent)} / 上界 ${percent(stats.upperPercent)}\n价格线：锚点下 ${stats.below} / 等于锚点 ${stats.equal} / 锚点上 ${stats.above}；完整区间：下方 ${stats.intervalsBelow} / 上方 ${stats.intervalsAbove} / 跨锚点 ${stats.intervalsCrossing}（端点等于锚点的区间计入对应一侧）`:'相对边界与锚点统计不可用';$('levels').hidden=!scheme;}
function updateExplanation(){
 const target=$('generation-content');target.replaceChildren();
 const add=(text:string)=>{const p=document.createElement('p');p.textContent=text;target.append(p);};
 add(dataset.history?`真实历史：${dataset.history.source.provider} 官方历史快照；合成未来仅用于显示验证。`:'真实历史不可用，无法核验配套 DEMO。');
 const f=dataset.forecast;
 if(!f){add('DEMO 元数据不可用；请修复文件后重载。');return;}
 add(generationExplanation(f));
 add(`未来来源：${f.source_kind} · generator_version：${f.generator_version} · seed：${f.seed}`);
 add(`演示锚点：${view?.format(f.anchor_time,true)??f.anchor_time} · ${f.anchor_price} USDT`);
 for(const scenario of f.scenarios)add(`${scenario.name}：${scenario.description||'文件未提供描述。'}`);
 const g=dataset.grids;
 add(g?`网格来源：${g.source_kind} · generator_version：${g.generator_version} · seed：${g.seed}。边界和价格层级直接来自独立网格文件，不由路径推导。`:'网格元数据不可用。');
}
async function reload(){const id=++request;controller?.abort();controller=new AbortController();$('load-status').textContent='正在校验本地文件 · 当前显示旧快照';const previousScheme=select('scheme').value;const visibility=new Map([...view?.paths??[]].map(([key,s])=>[key,s.options().visible]));const next=await loadDataset(controller.signal);if(id!==request)return;view?.destroy();view=undefined;dataset=next;$('legend').replaceChildren();const historyLabel=document.createElement('span');historyLabel.className='legend-item';historyLabel.textContent='▮ 真实历史 K 线';$('legend').append(historyLabel);$('errors').hidden=!next.errors.length;$('errors').textContent=next.errors.join('\n');
 if(next.history){view=new WeatherChart($('chart'),next.history,next.forecast,hover);view.setTimezone(select('timezone').value==='UTC'?'UTC':Intl.DateTimeFormat().resolvedOptions().timeZone);if(next.forecast)view.setWindow(Number(select('window').value));for(const [i,s]of(next.forecast?.scenarios??[]).entries()){const label=document.createElement('label');label.className='legend-item path-toggle';const input=document.createElement('input');input.type='checkbox';input.checked=visibility.get(s.id)??true;input.setAttribute('aria-label',s.name);view.setPath(s.id,input.checked);input.onchange=()=>view?.setPath(s.id,input.checked);const swatch=document.createElement('i');swatch.className='path-swatch';swatch.style.borderColor=colors[i%colors.length];swatch.style.borderStyle=['solid','dashed','dotted'][i%3];label.append(input,swatch,document.createTextNode(s.name));$('legend').append(label);}}
 select('scheme').replaceChildren();for(const s of next.grids?.schemes??[]){const option=document.createElement('option');option.value=s.id;option.textContent=`${s.name} / ${s.mode.label}`;select('scheme').append(option);}select('scheme').value=next.grids?.schemes.some(s=>s.id===previousScheme)?previousScheme:next.grids?.default_scheme_id??'';
 select('window').disabled=!next.forecast;select('scheme').disabled=!next.grids;($('grid-visible')as HTMLInputElement).disabled=!next.grids;($('reset')as HTMLButtonElement).disabled=!next.history;select('timezone').disabled=!next.history;updateGrid();updateMeta();updateExplanation();hover(undefined);$('load-status').textContent=next.errors.length?'加载存在错误 · 无效图层已清除':'本地文件已校验 · 固定 DEMO / 尚未接入评估';
}
$('reset').onclick=()=>view?.reset();$('window').onchange=()=>view?.setWindow(Number(select('window').value));$('timezone').onchange=()=>{view?.setTimezone(select('timezone').value==='UTC'?'UTC':Intl.DateTimeFormat().resolvedOptions().timeZone);updateMeta();updateExplanation();};$('scheme').onchange=updateGrid;$('grid-visible').onchange=updateGrid;$('reload').onclick=()=>void reload();
if(new URLSearchParams(location.search).has('test'))Object.assign(window,{chartTest:{snapshot:()=>view?.diagnostics()??{historyCount:0,pathCount:0,gridLineCount:0,activeCharts:0},setRange:(from:number,to:number)=>view?.setRange(from,to),reload}});
void reload();window.addEventListener('pagehide',(event)=>{if(event.persisted)return;controller?.abort();view?.destroy();});
